
title: My Resume
url: 'http://webjeda.com'
baseurl: '/Resume' #change it according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
style: styles-6


#Profile information
name: Jake Armstrong
tagline: Cloud Architect
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: hi@jakearmstrong.me
phone: 435 215 6809
website: blog.jakearmstrong.me #do not add http://
linkedin: jakemarmstrong
github: aristotlejake
twitter: '@jakemarmstrong'


# Tracker
analytics: UA-83979019-1
#Update all the sections by editing the files inside _includes folder.
